name: post-merge-continue
on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  continue:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'automation:continue') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find latest prompt body (merged)
        id: prompt
        shell: bash
        run: |
          set -e
          FILE=$(ls -t .github/auto/prompt-*.md 2>/dev/null | head -n 1 || true)
          if [ -z "$FILE" ]; then
            echo "body=No previous prompt found." >> $GITHUB_OUTPUT
          else
            echo "body<<EOF" >> $GITHUB_OUTPUT
            cat "$FILE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Open a new follow-up issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TITLE="Continue: follow-up tasks after PR #${{ github.event.pull_request.number }}"
          BODY=$(cat <<'MD'
/auto edit long diagnose autorepair test-build lint-fix cooldown-15s time-120m steps-2
이전 PR의 작업을 이어서 다음 우선순위를 진행합니다.
- 실패/미흡 테스트 보완
- 경량 e2e 1~2개 추가(가능 시)
- README 보강

[Context from previous run]
MD
)
          BODY="$BODY

${{ steps.prompt.outputs.body }}"
          gh issue create --title "$TITLE" --body "$BODY" --label "automation:run"
